### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by berezovskazlata** [berezovskazlata/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by dmberezovskyi** [comment]
March 1999
In March 1999, Musk co-founded X.com, an online financial services and e-mail payment company, with US$10 million from the sale of Zip2.

October 2000
Musk was ousted in October 2000 from his role as CEO of PayPal (although he remained on the board) due to disagreements with other company leadership, notably over his desire to move PayPal's Unix-based infrastructure to Microsoft Windows. 

2001
In 2001, Musk conceptualized Mars Oasis, a project to land a miniature experimental greenhouse on Mars, containing food crops growing on Martian regolith, in an attempt to regain public interest in space exploration. 

May 2002
Musk founded Space Exploration Technologies, or SpaceX, in May 2002 with US$100 million of his early fortune. Musk became the chief executive officer (CEO) and chief technology officer (CTO) of the Hawthorne, California-based company. SpaceX develops and manufactures space launch vehicles with a focus on advancing the state of rocket technology. 

October 2002
In October 2002, PayPal was acquired by eBay for US$1.5 billion in stock, of which Musk received US$165 million. 

July 2003
Tesla, Inc. (originally Tesla Motors) was incorporated in July 2003 by Martin Eberhard and Marc Tarpenning, who financed the company until the Series A round of funding.

September 2008
In September 2008, SpaceX's Falcon 1 rocket became the first privately funded liquid-fueled vehicle to put a satellite into Earth orbit.

2010
In 2010, the Musk Foundation collaborated with SolarCity to donate a 25-kW solar power system to the South Bay Community Alliance's hurricane response center in Coden, Alabama.

May 25, 2012
On May 25, 2012, the SpaceX's vehicle, Dragon berthed with the ISS, making history as the first commercial company to launch and berth a vehicle to the International Space Station.

2013
By 2013, SolarCity was the second largest provider of solar power systems in the United States.

January 2015
In January 2015, Musk made a guest appearance playing himself on The Simpsons in an episode titled "The Musk Who Fell to Earth"; the episode poked fun at many of Musk's ideas.

January 2015
Musk donated US$10 million to the Future of Life Institute in January 2015, to run a global research program aimed at keeping artificial intelligence beneficial to humanity.

May 12, 2017
Hyperloop One, a company unaffiliated with Musk, had announced that it had done its first successful test run on its DevLoop track in Nevada on July 13, 2017. It was on May 12, 2017, at 12:02 a.m. and had lasted 5.3 seconds, reaching a top speed of 70 mph.

December 2017
At a Tesla event on the sidelines of the Conference on Neural Information Processing Systems in December 2017, Musk stated that:

2019
On 19th February 2019, according to Forbes, Musk stated in a tweet that Tesla would build half a million cars in 2019. Dane Butswinkas, who arrived on 17th December to serve as Tesla’s General Counsel reporting to Musk and likely reviewing his tweets after the settlement agreement was reached, resigned on 21st February.
