### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by berezovskazlata** [berezovskazlata/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by dmberezovskyi** [comment]
Musk created a video game at age 12, sold it for $500
Musk created a video game called ‘Blastar’ at age 12. He wrote the computer programming for the game which was science fiction inspired game similar to Space Invaders. The game was later published by a South African company who paid Musk $500 for its source code.  

Musk has six children, all of whom are boys 
Musk has six children, all of whom are boys. His first wife gave birth to a set of twins (Xavier and Griffin) in 2004 and then triplets (Kai, Saxon and Damian) in 2006. Currently, Musk and his first wife Justine share custody of the five children.  

Musk also fathered a son in 2002 who died in just 10 weeks due to Sudden Infant Death Syndrome (SIDS).  

In 2018, Musk began dating Canadian Singer Claire Elise Boucher and two years later had a son with her named X Æ A-12 Musk (pronounced x-ash-a-12). 

Musk’s annual salary at Tesla is $1 
Yes, Elon Musk just draws an annual salary of $1 from Tesla while most of his fortune comes from his share in stock. Although, there was a time when Elon couldn’t even make ends meet as he lived off just $1 buying hot dogs and oranges in bulk. 

Musk has made appearances in Hollywood movies and sitcoms 
Musk has made cameos in American sitcoms like The Big Bang Theory, Simpsons and South Park.  

Musk wanted to sell Tesla  
It was in 2013 that Musk almost sold Tesla to Google for $11 billion. At that time Tesla was not the company it is today and was leaking copious amounts of money for Elon. At that time, he reached out to Alphabet CEO Larry Page for a takeover.  

He had even reached out to Apple CEO Tim Cook to sell the company but Tim refused to meet Musk.
